#!/bin/bash

CLANGFORMAT_INPUT_DIR=${CMSSW_BASE}/src/JMETriggerAnalysis

if ! [ -d ${CLANGFORMAT_INPUT_DIR} ]; then
  printf "%s\n" "ERROR -- target directory does not exist: ${CLANGFORMAT_INPUT_DIR}"
  exit 1
fi

for file_i in $(ls ${CLANGFORMAT_INPUT_DIR}/*/*/*.{h,hpp,cc,cpp,cu} 2> /dev/null); do
  clang-format -style=file -i ${file_i}
done
unset file_i CLANGFORMAT_INPUT_DIR
