#!/bin/bash

CLANGTIDY_INPUT_DIR=${CMSSW_BASE}/src/JMETriggerAnalysis

if ! [ -d ${CLANGTIDY_INPUT_DIR} ]; then
  printf "%s\n" "ERROR -- target directory does not exist: ${CLANGTIDY_INPUT_DIR}"
  exit 1
fi

if [ -z "${ROOT_INCLUDE_PATH}" ]; then
  printf "%s\n" "ERROR -- environment variable ROOT_INCLUDE_PATH is empty"
  exit 1
fi

find ${CLANGTIDY_INPUT_DIR} -regex '.*\.\(cpp\|hpp\|cu\|c\|cc\|h\)' -exec clang-tidy -fix-errors {} -- -x c++ -std=c++2a -I${ROOT_INCLUDE_PATH//:/ -I} \;

unset -v CLANGTIDY_INPUT_DIR
