#!/bin/bash

CLANGFORMAT_INPUT_DIR=${CMSSW_BASE}/src/JMETriggerAnalysis

if ! [ -d ${CLANGFORMAT_INPUT_DIR} ]; then
  printf "%s\n" "ERROR -- target directory does not exist: ${CLANGFORMAT_INPUT_DIR}"
  exit 1
fi

find ${CLANGFORMAT_INPUT_DIR} -regex '.*\.\(cpp\|hpp\|cu\|c\|cc\|h\)' -exec clang-format -style=file -i {} \;

unset -v CLANGFORMAT_INPUT_DIR
