#!/bin/bash

CLANGTIDY_INPUT_DIR=${CMSSW_BASE}/src/JMETriggerAnalysis

if ! [ -d ${CLANGTIDY_INPUT_DIR} ]; then
  printf "%s\n" "ERROR -- target directory does not exist: ${CLANGTIDY_INPUT_DIR}"
  exit 1
fi

if ! [ -d ${CMSSW_BASE}/src ]; then
  printf "%s\n" "ERROR -- target directory does not exist [\${CMSSW_BASE}/src]: ${CMSSW_BASE}/src"
  exit 1
fi

if ! [ -d ${ROOTSYS}/include ]; then
  printf "%s\n" "ERROR -- target directory does not exist [\${ROOTSYS}/include]: ${ROOTSYS}/include"
  exit 1
fi

find ${CLANGTIDY_INPUT_DIR} -regex '.*\.\(cpp\|hpp\|cu\|c\|cc\|h\)' -exec clang-tidy -fix-errors {} -- -x c++ -std=c++2a -I${CMSSW_BASE}/src -I${ROOTSYS}/include \;

unset -v CLANGTIDY_INPUT_DIR
